# The manifest for the "carevillage-pipeline" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

name: carevillage-pipeline
version: 1

source:
  provider: GitHub
  properties:
    repository: erikweller/material-kit-react
    branch: main
    connection_arn: arn:aws:codestar-connections:us-east-1:952530696403:connection/6689129c-6c87-43d4-a325-583a4fb5b227

stages:
  - name: dev
    test_commands:
      - echo "✔️ Validating CareVillage dev build"
      - echo "🚀 Deploying to dev environment"
