# The manifest for the "carevillage-pipeline" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: carevillage-pipeline

# The version of the schema used in this template.
version: 1

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/erikweller/material-kit-react
    connection_arn: arn:aws:codestar-connections:us-east-1:952530696403:connection/3db2ade9-ed7f-4f09-a98f-5f698c2427b0


# This section defines the order of the environments your pipeline will deploy to.
stages:
  - # The name of the environment.
    name: dev
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

  - # The name of the environment.
    name: prod
    requires_approval: true
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

