name: carevillage-pipeline
version: 1

source:
  provider: GitHub
  properties:
    repository: erikweller/material-kit-react
    branch: main
    connection_arn: arn:aws:codestar-connections:us-east-1:952530696403:connection/6689129c-6c87-43d4-a325-583a4fb5b227

stages:
  - name: dev
    test_commands:
      - echo "✅ Validating CareVillage dev environment"
