name: carevillage-pipeline
version: 1

source:
  provider: GitHub
  properties:
    repository: erikweller/material-kit-react
    branch: main
    connection_name: copilot-erikw-material-kit-react

stages:
  - name: dev
    test_commands:
      - echo "✅ Validating CareVillage dev environment"
